services:  
  qlever: 
    environment:
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      LETSENCRYPT_HOST: ${HOST_NAME_QLEVER}
      VIRTUAL_HOST: ${HOST_NAME_QLEVER}
      VIRTUAL_PORT: 7000
    expose:
      - 7000
    networks:
    - internal
    - proxy
    
  qlever-ui:
    environment:
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      LETSENCRYPT_HOST: ${HOST_NAME_QLEVER_UI}
      VIRTUAL_HOST: ${HOST_NAME_QLEVER_UI}
      VIRTUAL_PORT: 7000
      CONTENT_SECURITY_POLICY: "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' blob:; script-src-elem 'self' 'unsafe-inline' 'unsafe-eval' blob: https://code.jquery.com https://maxcdn.bootstrapcdn.com; style-src-elem 'self' 'unsafe-inline' https://code.jquery.com https://maxcdn.bootstrapcdn.com; img-src 'self' https: data: blob:; connect-src 'self';"
    expose:
      - 7000
    networks:
    - internal
    - proxy

volumes:
  qlever-ui-db:

networks:
  internal:
  proxy:
    name: ${PROXY_NETWORK_NAME}
    external: true
