services:  
  qlever: 
    environment:
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      LETSENCRYPT_HOST: ${HOST_NAME_QLEVER}
      VIRTUAL_HOST: ${HOST_NAME_QLEVER}
      VIRTUAL_PORT: 7000
    networks:
    - internal
    - proxy
    
  qlever-ui:
    environment:
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      LETSENCRYPT_HOST: ${HOST_NAME_QLEVER_UI}
      VIRTUAL_HOST: ${HOST_NAME_QLEVER_UI}
      VIRTUAL_PORT: 7000
    networks:
    - internal
    - proxy

volumes:
  qlever-ui-db:

networks:
  internal:
  proxy:
    name: ${PROXY_NETWORK_NAME}
    external: true
